name: CI/CD - Build & Deploy OVP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Build y Deploy
        run: |
          cd /opt/prototipo_OVP
          git pull origin main
          cd despliegue
          docker compose down
          docker compose up -d --build
          docker image prune -f
          echo "✅ Deploy completado"